describe("forget password functionality",()=>{
    it("test case forget password",()=>{
        cy.visit('https://parabank.parasoft.com/parabank/index.htm')
        cy.log('launch the application')
        cy.get('div:nth-child(3) div:nth-child(1) div:nth-child(2) p:nth-child(2) > a:nth-child(1)').click()
        cy.log('move to forget password page')
        cy.log("then fill require detail")
        cy.get("#firstName").type("Anil")
        cy.log("enter first name")
        cy.get("#lastName").type("kumar")
        cy.log("enter last name")
        cy.get("input[id='address.street']").type("Noida")
        cy.log("enter address")
        cy.get("input[id='address.city']").type("Noida")
        cy.log("enter city")
        cy.get("input[id='address.state']").type("UP")
        cy.log("enter state")
        cy.get("input[id='address.zipCode']").type("1000")
        cy.log("enter zipcode")
        cy.get("input[id='ssn']").type("66666666")
        cy.log("enter ssn number")
        cy.get("table.form2:nth-child(1) tbody:nth-child(1) tr:nth-child(8) td:nth-child(2) > input.button").click()
        cy.log("enter registration button")
        
    })
})