
/// <reference types="cypress">
describe('Registration application',()=>{
    it("Registration test case",()=>{
        cy.visit("https://parabank.parasoft.com/parabank/index.htm")
        cy.get('#loginPanel > :nth-child(3) > a').click()
        cy.log('visit registraion page successfully')
        cy.log('enter first name')
        cy.get('input[id="customer.firstName"]').type("preeti")
        cy.log('enter last name')
        cy.get('input[id="customer.lastName"]').type("kumari")
        cy.log('enter address')
        cy.get('input[id="customer.address.street"]').type("Noida")
        cy.log('enter city')
        cy.get('input[id="customer.address.city"]').type("Noida")
        cy.log('enter state')
        cy.get('input[id="customer.address.state"]').type("UP")
        cy.log('enter zipcode')
        cy.get('input[id="customer.address.zipCode"]').type("1000")
        cy.log('enter phone number')
        cy.get('input[id="customer.phoneNumber"]').type("8978563423")
        cy.log('enter ssn code')
        cy.get('input[id="customer.ssn"]').type("66666666")
        cy.log('enter user name')
        cy.get('input[id="customer.username"]').type("Kajaltes")
        cy.log('enter password')
        cy.get('input[id="customer.password"]').type("test123")
        cy.log(' Re enter password')
        cy.get('input[id="repeatedPassword"]').type("test123")
        cy.log('enter submit button')
        cy.get('[colspan="2"] > .button').click()
        cy.log('you can fill all detail according to registration then registration will successfully')
        cy.get('span[id="customer.username.errors"]').contains('This username already exists.')
        cy.log('you can fill all detail according to registration then registration will successfully if you have enter same detail the show you message This username already exists') 
    })
})